config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'users'
  devise_for :property_owners, path: 'property_owners'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get 'my_profile', to: 'users#my_profile'

  resources :properties, only: %i[show new create edit update destroy] do
    get 'my_properties', on: :collection
    resources :property_reservations, only: %i[create show], shallow: true do
      post 'accept', on: :member
    end
  end
  resources :property_types, only: [:show, :new, :create]

  namespace :api do
    namespace :v1 do
      resources :properties, only: %i[index show create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
    belongs_to :property_type
    belongs_to :property_owner
    has_many :property_reservations, dependent: :destroy

    validates :title, :description, :rooms,
              :bathrooms, :daily_rate, :property_type_id,
              presence: true
    # validates :pets, presence: true
    # validates :parking_slot, presence: true
    
end

app/models/property_owner.rb
class PropertyOwner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :properties
end

app/models/property_reservation.rb
class PropertyReservation < ApplicationRecord
  belongs_to :property
  belongs_to :user

  before_save :calculate_total_value
  before_create :generate_code
  validates :code, uniqueness: true
  validate :end_date_greater_than_start_date
  validate :start_date_in_the_future

  enum status: { pending: 5, accepted: 10, rejected: 20 }

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(8).upcase
    generate_code if PropertyReservation.exists?(code: code)
  end

  def calculate_total_value
    self.total_value = (end_date - start_date).to_i * property.daily_rate
  end

  def end_date_greater_than_start_date
    if start_date >= end_date
      errors.add(:end_date, 'deve ser maior que a Data de Início')
    end
  end

  def start_date_in_the_future
    if start_date < Date.today
      errors.add(:start_date, 'não pode ser em datas passadas')
    end
  end
end

app/models/property_type.rb
class PropertyType < ApplicationRecord
    has_many :properties
    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :property_reservations
  has_many :properties, through: :property_reservations
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ActionController::API
  rescue_from ActiveRecord::ActiveRecordError, with: :render_generic_error
  rescue_from ActiveRecord::RecordNotFound, with: :render_not_found

  private

  def render_not_found(e)
    render status: 404, json: '{ "message": "Objeto não encontrado" }'
  end
  
  def render_generic_error(e)
    render status: 500, json: '{ "message": "Falha ao consultar Banco de Dados" }'
  end
end

app/controllers/api/v1/properties_controller.rb
class Api::V1::PropertiesController < Api::V1::ApiController
  def index
    @properties = Property.all
    render json: @properties.as_json(except: %i[created_at updated_at property_type_id],
                                     include: { property_type: { only: %i[name] } })
  end

  def show
    @property = Property.find(params[:id])
    render json: @property
  end

  def create
    @property = Property.create!(property_params)
    render json: @property, status: 201
  end
  
  private

  def property_params
    params.require(:property).permit(:title, :description, :rooms, :parking_slot,
                                     :bathrooms, :pets,
                                     :daily_rate,
                                     :property_type_id, :property_owner_id)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @properties = Property.all()
        @property_types = PropertyType.all()
    end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
    before_action :authenticate_property_owner!, only: [:new, :create, :edit, :update, :destroy]

    def show
        @property = Property.find(params[:id])
        @property_reservation = PropertyReservation.new()
    end
    
    def new
        @property = Property.new()
    end

    def create
        @property = Property.new(property_params)
        @property.property_owner = current_property_owner

        if @property.save
            redirect_to @property
        else
            render :new
        end
    end

    def my_properties
        @properties = current_property_owner.properties
    end

    def edit
        @property = Property.find(params[:id])
    end

    def update
        @property = Property.find(params[:id])

        if @property.update(property_params)
            redirect_to @property
        else
            render :edit
        end
    end
    
    def destroy
        @property = Property.find(params[:id])

        if @property.destroy
            redirect_to my_properties_properties_path
        else

        end
    end
    
    private

    def property_params
        params.require(:property).permit(:title, :description, :rooms,
                                         :parking_slot, :bathrooms, :pets,
                                         :daily_rate, :property_type_id)
    end

end

app/controllers/property_reservations_controller.rb
class PropertyReservationsController < ApplicationController
    def show
        @property_reservation = PropertyReservation.find(params[:id])
    end

    def create
        @property_reservation = current_user.property_reservations.new(property_reservation_params)
        @property_reservation.property = Property.find(params[:property_id])
        @property_reservation.save
        PropertyReservationMailer
        .with(reservation: @property_reservation)
        .notify_new_reservation()
        .deliver_now()

        redirect_to @property_reservation, notice: t('.success')
    end

    def accept
        @property_reservation = PropertyReservation.find(params[:id])
        @property_reservation.accepted!
        redirect_to @property_reservation.property
    end

    private

    def property_reservation_params
        params.require(:property_reservation).permit(:start_date, :end_date, :guests)
    end
end

app/controllers/property_types_controller.rb
class PropertyTypesController < ApplicationController
    def show
        id = params[:id]
        @property_type = PropertyType.find(id)
    end
    
    def new
        @property_type = PropertyType.new()
    end
    
    def create
        @property_type = PropertyType.new(property_type_params)

        if @property_type.save
            redirect_to @property_type
        else
            render :new
        end
    end

    private

    def property_type_params
        params.require(:property_type).permit(:name)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def my_profile
        @user = current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<header>
    <h1>🏡 Flats</h1>
    <h3>Boas vindas ao sistema de locação de apartamentos</h3>
</header>
<main>
    <aside>
        <h2>Filtrar Por Tipo:</h2>
        <nav>
            <% @property_types.each do |pt| %>
                <%= link_to pt.name, property_type_path(pt.id) %>
            <% end %>
        </nav>
    </aside>
    <section>
        <h1>Imóveis Disponíveis</h1>
        <% if @properties.empty? %>
            <div><span>Nenhum imóvel disponível</span></div>
        <% end %>
        <table>
            <thead>
                <tr>
                    <th>Título</th>
                    <th>Descrição</th>
                    <th>Quartos</th>
                </tr>
            </thead>
            <tbody>
                <% @properties.each do |p| %>
                    <%= render p %>
                <% end %>
            </tbody>
        </table>
    </section>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flats-TD7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav>
        <% if property_owner_signed_in? %>
          <p><%= current_property_owner.email %></p>
          <p><%= link_to('Logout', destroy_property_owner_session_path, method: :delete) %></p>
          <div>
              <nav>
                  <%= link_to 'Meus Imóveis', my_properties_properties_path %><br>
                  <%= link_to 'Cadastrar Imóvel', new_property_path %><br>
                  <%= link_to 'Cadastrar Tipo de Imóvel', new_property_type_path %>
                  <hr>
              </nav>
          </div>
        <% elsif user_signed_in? %>
          <p><%= link_to current_user.email, my_profile_path %></p>
          <p><%= link_to('Logout', destroy_user_session_path, method: :delete) %></p>
        <% else %>
          <p><%= link_to('Entrar como Proprietário do Imóvel', new_property_owner_session_path) %></p>
          <p><%= link_to('Entrar como Locador', new_user_session_path) %></p>
        <% end %>
      </nav>
      <% if notice %>
        <p class="alert alert-info"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-warning"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_with(model: @property) do |f| %>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
        <% @property.errors.full_messages_for(:title).each do |message| %>
            <div class="form-error"><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= f.label :description %>
        <%= f.text_field :description %>
        <% @property.errors.full_messages_for(:description).each do |message| %>
            <div class="form-error"><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= f.label :rooms %>
        <%= f.number_field :rooms %>
        <% @property.errors.full_messages_for(:rooms).each do |message| %>
            <div class="form-error"><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= f.label :bathrooms %>
        <%= f.number_field :bathrooms %>
        <% @property.errors.full_messages_for(:bathrooms).each do |message| %>
            <div class="form-error"><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= f.label :daily_rate %>
        <%= f.text_field :daily_rate %>
        <% @property.errors.full_messages_for(:daily_rate).each do |message| %>
            <div class="form-error"><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= f.label :property_type_id %>
        <%= f.collection_select :property_type_id, PropertyType.all, :id, :name, prompt: 'Escolha um Tipo' %>
        <% @property.errors.full_messages_for(:property_type_id).each do |message| %>
            <div class="form-error"><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= f.check_box :pets %>
        <%= f.label :pets %>
        <% @property.errors.full_messages_for(:pets).each do |message| %>
            <div class="form-error"><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= f.check_box :parking_slot %>
        <%= f.label :parking_slot %>
        <% @property.errors.full_messages_for(:parking_slot).each do |message| %>
            <div class="form-error"><%= message %></div>
        <% end %>
    </div>
    <%= f.submit "Enviar" %>
<% end %>

app/views/properties/_property.html.erb
<div class="property-table">
    <tr>
        <td><%= link_to(property.title, property_path(property.id)) %></td>
        <td><%= property.description %></td>
        <td>Quartos: <%= property.rooms %></td>
    </tr>
</div>

app/views/properties/edit.html.erb
<header>
    <h1>🏡 Edição de Imóvel</h1>
    <nav>
        <%= link_to('Voltar', root_path) %>
        <hr>
    </nav>
</header>
<main>
    <%= render partial: "form" %>
</main>

app/views/properties/my_properties.html.erb
<header>
    <h1>🏡 Meus Imóveis</h1>

    <nav>
        <%= link_to('Voltar', root_path)%>
        <hr>
    </nav>
</header>

<main>
    <div>
        <% if @properties.empty? %>
            <div>
                <span>Você ainda não cadastrou imóveis</span>
                <%= link_to("Cadastre seu primeiro imóvel agora", new_property_path) %>
            </div>
        <% end %>
        <table>
            <thead>
                <tr>
                    <th>Título</th>
                    <th>Descrição</th>
                    <th>Quartos</th>
                    <th colspan="2">Ações</th>
                </tr>
            </thead>
            <tbody>
                <% @properties.each do |p| %>
                    <tr>
                        <td><%= link_to(p.title, property_path(p.id)) %></td>
                        <td><%= p.description %></td>
                        <td>Quartos: <%= p.rooms %></td>
                        <td><%= link_to "Editar", edit_property_path(p.id) %></td>
                        <td><%= link_to "Deletar", property_path(p.id), method: :delete,
                                        data: { confirm: "Quer apagar esse Imóvel?" } %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</main>

app/views/properties/new.html.erb
<header>
    <h1>🏡 Cadastro de Imóvel</h1>
    <nav>
        <%= link_to('Voltar', root_path) %>
        <hr>
    </nav>
</header>
<main>
    <%= render partial: "form" %>
</main>

<%# Modo preguiça para erros abaixo %>
<%# if @property.errors.any? %>
    <%# <ul> %>
        <%# @property.errors.full_messages.each do |error| %>
            <%# <li><%= error </li> %>
        <%# end %> 
    <%# </ul> %>
<%# end %>

app/views/properties/show.html.erb
<header>
    <h1>🏡 Vizualização do Imóvel</h1>

    <nav>
        <%= link_to('Voltar', root_path)%>
        <hr>
    </nav>
</header>

<main>
    <div>
        <h1>
            <%= @property.title %>
        </h1>
        <h2><%= @property.description %></h2>

        <dl>
            <dt>Tipo: </dt>
            <dd><%= @property.property_type.name %></dd>

            <dt>Quartos: </dt>
            <dd><%= @property.rooms %></dd>

            <dt>Banheiros: </dt>
            <dd><%= @property.bathrooms %></dd>

            <dt>Aceita Pets: </dt>
            <% if @property.pets? %>
                <dd>Sim</dd>
            <% else %>
                <dd>Não</dd>
            <% end %>

            <dt>Estacionamento: </dt> 
            <% if @property.parking_slot? %>
                <dd>Sim</dd>
            <% else %>
                <dd>Não</dd>
            <% end %>

            <dt>Diária: </dt>
            <dd><%= number_to_currency(@property.daily_rate) %></dd>

            <dt>Imóvel de: </dt>
            <dd><%= @property.property_owner.email %></dd>
        </dl>
    </div>

    <div>
        <% if property_owner_signed_in? && @property.property_owner == current_property_owner %>
            <h3>Reservas</h3>
            <% @property.property_reservations.each do |pr| %>
                <h4>Reserva de <%= pr.user.email %></h4>
                <dl>
                    <dt>Data de Início:</dt>
                    <dt><%= I18n.l(pr.start_date) %></dt>

                    <dt>Data de Saída:</dt>
                    <dt><%= I18n.l(pr.end_date) %></dt>

                    <dt>Total de Pessoas:</dt>
                    <dt><%= pr.guests %></dt>

                    <dt>Status:</dt>
                    <dt><%= I18n.t(pr.status) %></dt>
                </dl>

                <%= link_to 'Aceitar Reserva', accept_property_reservation_path(pr.id), method: :post %>
            <% end %>

        <% elsif user_signed_in? %>
            <h3>Reserve Agora</h3>
            <%= form_with model: [@property, @property_reservation] do |f| %>
                <div>
                    <%= f.label :start_date %>
                    <%= f.date_field :start_date %>
                    <% @property_reservation.errors.full_messages_for(:start_date).each do |message| %>
                        <div class="form-error"><%= message %></div>
                    <% end %>
                </div>
                <div>
                    <%= f.label :end_date %>
                    <%= f.date_field :end_date %>
                    <% @property_reservation.errors.full_messages_for(:end_date).each do |message| %>
                        <div class="form-error"><%= message %></div>
                    <% end %>
                </div>
                <div>
                    <%= f.label :guests %>
                    <%= f.number_field :guests, step: 1, min: 1 %>
                    <% @property_reservation.errors.full_messages_for(:guests).each do |message| %>
                        <div class="form-error"><%= message %></div>
                    <% end %>
                </div>
                <%= f.submit "Enviar Reserva" %>
            <% end %>
        <% end %>
    </div>
</main>

app/views/property_owners/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/property_owners/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/property_reservations/show.html.erb
<h3>Reserva do Imóvel</h3>
<dl>
    <dt>Data de Início</dt>
    <dd><%= l @property_reservation.start_date %></dd>

    <dt>Data de Término</dt>
    <dd><%= l @property_reservation.end_date %> </dd>

    <dt>Quantidade de Pessoas</dt>
    <dd><%= @property_reservation.guests %> </dd>

    <dt>Valor Total</dt>
    <dd><%= number_to_currency @property_reservation.total_value %></dd>
</dl>

<%= link_to 'Cancelar Reserva' %>

app/views/property_types/new.html.erb
<header>
    <h1>Cadastro de Tipo de Imóvel</h1>

    <nav>
        <%= link_to('Voltar', root_path) %>
        <hr>
    </nav>
</header>
<main>
    <%= form_with(model: @property_type) do |f| %>
        <div>
            <%= f.label :name %>
            <%= f.text_field :name %>
            <% @property_type.errors.full_messages_for(:name).each do |message| %>
                <div class="form-error"><%= message %></div>
            <% end %>
        </div>
        <%= f.submit "Enviar" %>
    <% end %>
</main>

app/views/property_types/show.html.erb
<header>
    <h1>Imóveis do tipo <%= @property_type.name %></h1>

    <nav>
        <%= link_to('Voltar', root_path) %>
        <hr>
    </nav>
</header>

<main>
    <h2>Imóveis Disponíveis</h2>
    <% if @property_type.properties.empty? %>
        <div><span>Nenhum imóvel disponível</span></div>
    <% end %>
    <table>
        <thead>
            <tr>
                <th>Título</th>
                <th>Descrição</th>
                <th>Quartos</th>
            </tr>
        </thead>
        <tbody>
            <% @property_type.properties.each do |p| %>
                <%= render p %>
            <% end %>
        </tbody>
    </table>
</main>

app/views/users/my_profile.html.erb
<h1>Meu Perfil</h1>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>